sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: DXv0znxm5/cfmhD29D46chkouV+JdideeU+D4aH1orEd1uKg0iKI5QUQzMDJJojGF91ey42q2bYwHqW+rW3Zuj8DMNd+5JQ9AMJ1rrWhm3tStu+hExBTgwZeS69+0DHzDJ5kv+dMSgvfYfYyvkiitii4pipiSUdO//AJUE82Tta+ALSz6bWFuKblht6GVCUJuIorcDD8bTx1BN+qrLyfmzFbOnS7R4SKqNgiP8e+kJwoAbZmI8ojZRi5+R7vSd4kSDsm/dkuYFGq3nwBzm95BW/n8qfLSvUjeQaihnErCtGED3I957DU6bvKPu5VUL7HddRzKk7oxWZt7E5SdEUwPeCm1rvzOF9nY1G8bTpUIpV5e0K7yDcoDwtPjo6cHRW4iTpIM7nPiikh+QSKAAvpNAXcNJlfG5gnEWlFBvx+DVJYwOYEw07/R90TlLvw1lBph4Rhq2j+9zKw+KS1LxZ1d561uqSz62AKJVwJbgq/zWlfbADnXJ8yjKLjrMrz9sfxxyJPIqOCKOq9ppmIHkt1EzZcDFS7k/LTRtH5tNOMQjOSf2c8B8QRBclu1kHbnKPidpK1G7lL1yo6G8B2MkxUoUBcoKOLEPIrhCAuNDn5OamuTguKrEFyPVuXmfUzmWQv6bmGbejPjOK78Q+xjWAJtH5f++dqI07ypRGUVZCnEs4=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Memoirs-of-the-Court-of-St.-Cloud--Being-secret-letters-from-a-gentleman-at-Paris-to-a-noblema__3892
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy